//! The `Executor` trait — the runtime contract between generated code and the pool.
//!
//! Code generated by `sasql::query!` calls methods on this trait. Both `Pool`
//! and `PoolConnection` implement it.

use tokio_postgres::types::ToSql;

use crate::error::{QueryError, SasqlError, SasqlResult};
use crate::pool::{Pool, PoolConnection};

/// Execute a prepared query and return raw rows.
///
/// This trait is sealed — it cannot be implemented outside of sasql-core.
/// The generated code calls `query_raw` and `execute_raw` on either `&Pool`
/// or `&PoolConnection`.
pub trait Executor: sealed::Sealed {
    /// Execute a query and return all rows.
    fn query_raw(
        &self,
        sql: &str,
        params: &[&(dyn ToSql + Sync)],
    ) -> impl std::future::Future<Output = SasqlResult<Vec<tokio_postgres::Row>>> + Send;

    /// Execute a query and return the number of affected rows.
    fn execute_raw(
        &self,
        sql: &str,
        params: &[&(dyn ToSql + Sync)],
    ) -> impl std::future::Future<Output = SasqlResult<u64>> + Send;
}

mod sealed {
    pub trait Sealed {}
    impl Sealed for super::Pool {}
    impl Sealed for super::PoolConnection {}
}

impl Executor for Pool {
    async fn query_raw(
        &self,
        sql: &str,
        params: &[&(dyn ToSql + Sync)],
    ) -> SasqlResult<Vec<tokio_postgres::Row>> {
        let conn = self.acquire().await?;
        conn.query_raw(sql, params).await
    }

    async fn execute_raw(
        &self,
        sql: &str,
        params: &[&(dyn ToSql + Sync)],
    ) -> SasqlResult<u64> {
        let conn = self.acquire().await?;
        conn.execute_raw(sql, params).await
    }
}

impl Executor for PoolConnection {
    async fn query_raw(
        &self,
        sql: &str,
        params: &[&(dyn ToSql + Sync)],
    ) -> SasqlResult<Vec<tokio_postgres::Row>> {
        // prepare_cached: prepares on first use, reuses on subsequent calls.
        // Named statements persist across borrows of the same connection.
        let stmt = self
            .inner
            .prepare_cached(sql)
            .await
            .map_err(pg_err_to_query)?;

        self.inner
            .query(&stmt, params)
            .await
            .map_err(pg_err_to_sasql)
    }

    async fn execute_raw(
        &self,
        sql: &str,
        params: &[&(dyn ToSql + Sync)],
    ) -> SasqlResult<u64> {
        let stmt = self
            .inner
            .prepare_cached(sql)
            .await
            .map_err(pg_err_to_query)?;

        self.inner
            .execute(&stmt, params)
            .await
            .map_err(pg_err_to_sasql)
    }
}

fn pg_err_to_query(e: tokio_postgres::Error) -> SasqlError {
    SasqlError::Query(QueryError {
        message: e.to_string(),
        pg_code: e.code().map(|c| c.code().to_owned()),
    })
}

fn pg_err_to_sasql(e: tokio_postgres::Error) -> SasqlError {
    SasqlError::from(e)
}
